api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='api-home'),
    path('Topics/', views.TopicListCreateView.as_view(), name='topic-list'),
    path('Topics/<str:topic_name>/', views.TopicArticleListCreateView.as_view(), name='topic-detail'),
    path('Articles/', views.ArticleListView.as_view(), name='article-list'),
    path('Articles/<int:pk>/', views.ArticleCommentListCreateView.as_view(), name='article-detail'),
    path('Comments/', views.CommentListView.as_view(), name='comment-list'),
    path('Comments/<int:pk>/', views.CommentMessageListCreateView.as_view(), name='comment-detail'),
    path('Messages/', views.MessageListView.as_view(), name='message-list'),
    path('Messages/<int:pk>/', views.MessageRetrieveView.as_view(), name='message-detail'),
]

base/urls.py
from atexit import register
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
    path('topics/<str:topic_name>/', views.topic_view, name='topic'),
    path('topics/<str:topic_name>/<int:article_id>', views.article_view, name='article'),
    path('add-msg/<comment_id>', views.add_comment_msg_view, name='add-msg')
    # path('add-topic/', views.add_topic_view, name='add-topic'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'), name='home'),
    path('api/', include('api.urls'), name='api'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

    @property
    def article_count(self):
        return self.article_set.count()


class Article(models.Model):
    title = models.CharField(max_length=50)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

    @property
    def topic_id(self):
        return self.topic.id

    @property
    def author_id(self):
        return self.user.id


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.user}: {self.content}'


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.content

    @property
    def author_id(self):
        return self.user.id

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Article, Message, Topic, Comment


class LoginForm(ModelForm):
    class Meta:
        model = User
        field = ['username', 'email', 'password1', 'password2']
        exclude = []


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class TopicForm(ModelForm):
    def __init__(self, *args,  **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False

    class Meta:
        model = Topic
        fields = '__all__'


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title']
        
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        
class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['content']

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponseNotFound, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Topic, Article, Comment
from .forms import MessageForm, TopicForm, ArticleForm, CommentForm, UserCreationForm
# Create your views here.


def home_view(request: HttpRequest):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('login')

        topic_form = TopicForm(request.POST)
        if topic_form.is_valid():
            topic_form.save()

    topic_form = TopicForm()
    topic_form.fields['name'].required = False
    topics = Topic.objects.all()
    topic_name = request.GET.get('name')

    if bool(topic_name):
        topics = topics.filter(name__icontains=topic_name)

    context = {
        'topics': topics,
        'form': topic_form
    }
    return render(request, 'base/home.html', context)


def login_view(request: HttpRequest):
    if request.user.is_authenticated:
        return redirect(request.META.get('HTTP_REFERER'))

    if request.method == 'GET':
        return render(request, 'base/login.html')

    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)

    if user is None:
        messages.error(request, 'login fail')
        return redirect('login')

    login(request, user)

    return redirect('home')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def register_view(request: HttpRequest):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'values are not valid')

    return render(request, 'base/register.html', {'form': form})


def topic_view(request: HttpRequest, topic_name):
    topic = get_object_or_404(Topic, name=topic_name)

    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('login')
        article_form = ArticleForm(request.POST)
        comment_form = CommentForm(request.POST)
        if article_form.is_valid() and comment_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user
            article.topic = topic
            article.save()

    article_form = ArticleForm()
    comment_form = CommentForm()
    articles = Article.objects.filter(topic=topic).order_by('-updated')
    title = request.GET.get('title')
    author = request.GET.get('author')

    if bool(title):
        articles = articles.filter(title__icontains=title)
    if bool(author):
        articles = articles.filter(author__username__icontains=author)

    context = {
        'topic': topic,
        'articles': articles,
        'article_form': article_form,
        'comment_form': comment_form
    }
    return render(request, 'base/topic.html', context)


def article_view(request: HttpRequest, topic_name, article_id):
    topic = get_object_or_404(Topic, name=topic_name)
    article = get_object_or_404(Article, pk=article_id)

    if article.topic.id != topic.id:
        return HttpResponseNotFound()

    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('login')

        comment_form = CommentForm(request.POST)
        if not comment_form.is_valid():
            messages.error(request, 'Cant add this invalid comment')
        else:
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.article = article
            comment.save()
            article.save()

    comments = Comment.objects.filter(article=article)
    comment_form = CommentForm()
    message_form = MessageForm()

    context = {
        'topic': topic,
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
        'message_form': message_form,
    }
    return render(request, 'base/article.html', context)


@login_required(login_url='login')
def add_comment_msg_view(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    message_form = MessageForm(request.POST)
    if message_form.is_valid():
        message = message_form.save(commit=False)
        message.comment = comment
        message.user = request.user
        message.save()

    return redirect(request.META.get('HTTP_REFERER'), '/')

base/templates/base/add_topic.html
{% extends 'base.html' %}



{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='add topic'>
    </form>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
            </li>
            {% endfor %}
    </ul>
    {% endif %}

{% endblock content %}

base/templates/base/article.html
{% extends 'base.html' %}

{% block content %}
    <h2>Topic: <a href="{% url 'topic' article.topic.name %}">{{article.topic.name}}</a></h2>
    <h2>title: {{ article.title }}</h2>
    <h4>created: {{ article.created }} ({{ article.created|timesince }})</h4>
    <h4>updated: {{ article.updated }} ({{ article.updated|timesince }})</h4>
    <h4>author: {{ article.user }}</h4>
    <p>{{ article.content }}</p>
    {% for message in article.message_set.all %}
        <li>@{{message.user}}: {{message.content}} ({{ message.created|timesince }})</li>
    {% endfor %}

    <hr>

    {% for comment in comments %}
        <p>
            {{ comment.user }}: {{ comment.content }}
        </p>
        {% for message in comment.message_set.all %}
        <li>@{{message.user}}: {{message.content}} ({{ message.created|timesince }})</li>
            
        {% endfor %}
            {% if request.user.is_authenticated %}
                <form action="{% url 'add-msg' comment.id %}" method="post">
                    {% csrf_token %}
                    {{ message_form}}
                    <input type="submit" value="leave message"">
                </form>
            {% else %}
                <a href="{% url 'login'%}">login to leave message</a>
            {% endif %}
        <hr>
    {% endfor %}

    {% if request.user.is_authenticated %}
        <form action="" method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit" value="add comment">
        </form>
    {% else %}
        <a href="{% url 'login' %}">login to add comment</a>
    {% endif %}


{% endblock content %}

base/templates/base/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to my website</h1>

    {% if request.user.is_authenticated %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Topic">
    </form>
    {% else %}
        <a href="{% url 'login' %}">login to add topic</a>

    {% endif %}
    

    <form action="" method="get">
        {{ form.as_p }}
        <input type="submit" value="Filter Topic(blank=All)">
    </form>
    <hr>

    

    {% for topic in topics %}
        
        <h3>
            <a href="{% url 'topic' topic.name %}">{{topic.name}} </a> has {{topic.article_set.count}} articles created: {{topic.created|timesince}} ago
        </h3>
        
        <hr>
    {% endfor %}

{% endblock content %}

base/templates/base/login.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" action="">
        {% csrf_token %}

        <label>Username:</label>
        <input type="text" name="username" placeholder="Enter Username" />
        <label>Password:</label>
        <input type="password" name="password" placeholder="Enter Password" />
        <input type="submit" value="Login" />
    </form>
    
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
            </li>
            {% endfor %}
    </ul>
    {% endif %}

{% endblock content %}

base/templates/base/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign up">
    </form>

{% endblock content %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
            </li>
            {% endfor %}
    </ul>
{% endif %}

base/templates/base/topic.html
{% extends 'base.html' %}

{% block content %}
    <h1>Topic: {{ topic }}</h1>
    <form action="" method='get'>
        <label>Search Title:</label>
        <input type="text" name="title" placeholder="title...">
        <label>Search Author:</label>
        <input type="text" name="author" placeholder="author...">
        
        <input type="submit" value="Search article">
    </form>

    <form action="" method="post">
        {% csrf_token %}
        
        {{article_form.as_p}}
        {{comment_form.as_p}}

        <input type="submit" value="add new article">

    </form>

    
    <hr>
    {% for article in articles %}
        <a href="{% url 'article' topic.name article.id %}">
            <h2>title: {{article.title}}</h2>
            <p>author: {{article.user}}</p>
            <p>created: {{article.created}}  ({{ article.created|timesince }} ago)</p>
        </a>
        <hr>
    {% endfor %}
{% endblock content %}